# Лампочки Yeelight
- platform: yeelight
  devices:
    192.168.1.104:
      name: Yeelight RGB_1
      transition: 350
      use_music_mode: True
    192.168.1.106:
      name: Yeelight RGB_2
      transition: 350
      use_music_mode: True
    192.168.1.108:
      name: Yeelight RGB_3
      transition: 350
      use_music_mode: True

- platform: group
  name: Lustra
  entities:
    - light.yeelight_rgb_1
    - light.yeelight_rgb_2
    - light.yeelight_rgb_3
