# ----- Включение света по одинарному клику ----- #
- alias: Lustra turn on with button
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001872b90
        click_type: single
  condition:
    - condition: state
      entity_id: light.lustra
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.lustra
      data_template:
        brightness_pct: 100
        kelvin: 4000

# ----- Выключение света по одинарному клику ----- #
- alias: Lustra turn off with the button
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0001872b90
        click_type: single
  condition:
    - condition: state
      entity_id: light.lustra
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.lustra